[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pysolve"
authors = [{name = "Liam", email = "Liam.RGodfrey@hotmail.co.uk"}]
requires-python = ">= 3.8"
readme = "README.md"
description = "toml"
license = {text = "BSD-3-Clause"}

keywords = ["workshop"]
dependencies = ["numpy"]
#classifiers = []
dynamic = ["version"]

[project.urls]
Homepage="https://github.com/Leeham1/polysolve"
Repository="https://github.com/Leeham1/polysolve.git"

[tool.setuptools.dynamic]
version = {attr = "polysolve.__version__"}
